[workspace]
members = [
    "crates/purec",
    "crates/hello",
    "crates/init",
    "crates/desk_display",
    "crates/desk_calc",
    "crates/desk_datetime",
    "crates/desk_clock",
    "crates/desk_calendar",
    "crates/desk_apps",
    "crates/apps_demo",
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "allow"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
